### ISSUE TITLE
Not opening in Mobile

### ISSUE THREAD

**Issue by infuerano** [bcedu/ValaSimpleHTTPServer#27] opened 2019-12-10 08:55 UTC
Hello,

Thank you for your work. I really appreciate it. Today I was using this app. I shared a link and it is opening in the PC browser. However, though I am on the same WIFI, I can't access it.

**Comment by bcedu** [comment] 2019-12-10 18:02
If it works from your computer it should work from yout mobile phone...
Are you sure you are at the same wifi? 

Is it the first timethat doesn't work from your mobile?

**Comment by infuerano** [comment] 2019-12-11 02:48
Yes sir... I am on the same WiFi. Tried 3 browsers but it doesn't do anything.

**Comment by infuerano** [comment] 2019-12-12 02:58
So i checked today also.. I was thinking maybe because of MIUI (lol), so used another device with stock rom. But things remain same..

**Comment by bcedu** [comment] 2019-12-12 06:07
I dont know what to say... O checked in my computer with two different phones and it worked. I checked at my work computer and it worked too...

Without testing in your computer/wifi i cant do anything more...

**Comment by bcedu** [comment] 2019-12-12 06:08
You could try changing the port that vserver is using, maybe this port is already used or blocked

**Comment by infuerano** [comment] 2019-12-12 06:10
Wwll, thank you.. i did changed the port and no result.. anyways, I am grateful for your work... Thank you for your time and consideration.

**Closed as completed** 2021-12-24 08:22 UTC

**Comment by NZTimKeegan** [comment] 2022-01-10 21:48
I had trouble connecting from my mobile initially too, and came across this issue looking for a solution.

The root cause was in fact the firewall rules on my machine. I added an inbound allow on port 8888 and everything worked. Posting this for future visitors in case it helps them too.

![image](https://user-images.githubusercontent.com/31173595/148844480-32444a3f-e626-4df3-8542-8b8e86ec3b32.png)
